# Generated by Django 5.1.7 on 2025-07-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
